version: '3.8'

services:

  db:
    image: postgres
    environment:
#      POSTGRES_DB: createmusic_dev
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
#    volumes:
#      - ./init:/docker-entrypoint-initdb.d/
#    volumes:
#      - db-data:/var/lib/postgresql/data

  app:
    build: .
    command: ["go", "run", "main.go"]
    volumes:
      - .:/go/src/go-createmusic
    ports:
      - "5000:5000"
#    restart: always
    depends_on:
      - db
#    links:
#      - db

#volumes:
#  db-data: